FROM dbeaver/cloudbeaver:latest
# RUN groupadd cloudbeaver
# RUN useradd -ms /bin/bash -g cloudbeaver cloudbeaver
# RUN chown -R cloudbeaver ./
# USER cloudbeaver

# ENV CB_SERVER_NAME = Test Server
# ENV CB_SERVER_URL = host.docker.internal:10000
# ENV CB_ADMIN_NAME = user
# ENV CB_ADMIN_PASSWORD = password

